### ISSUE TITLE
Native_HookValueFloat should be a float and not an int?

### ISSUE THREAD

**Issue by torridgristle** [nosoop/tf2attributes#3]
https://github.com/nosoop/tf2attributes/blob/6e73ccb9b28c0a7464c21c099d5db1777998b9ae/scripting/tf2attributes.sp#L652

It seems that this should be a float and not an int, given that it's got float in the name.

**Comment by nosoop** [comment]
Technically correct; thanks for the eyes.  This is primarily a holdover from when the `NativeCall` callback was defined as below, which always returned `int` (the bits remain the same regardless of the defined return type):

https://github.com/alliedmodders/sourcemod/blob/41a9889cddc745f4d6cab72693dbf37be16f504c/plugins/include/functions.inc#L360-L369

Correctness-wise it should be changed, but otherwise they behave exactly the same (except setting it as `float` throws a compile error on compilers pre-1.10, which shouldn't be in use at this time anyways).

Will probably push a commit for the backport PR @ FlaminSarge/tf2attributes#37 though, so it lands in upstream once they get around to it.
